version: '3.8'

services:
  sshd:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_USERNAME: ${SSH_USERNAME:-my_user}
        ENABLE_SUDO: ${ENABLE_SUDO:-false}
    volumes:
      - sshd_home:/home/${SSH_USERNAME:-my_user}
      - sshd_etc:/etc
      - sshd_var_lib:/var/lib
      - sshd_usr_local:/usr/local
    ports:
      - ${SSH_PORT:-2222}:22
      - 3000:300O

volumes:
  sshd_home:
  sshd_etc:
  sshd_var_lib:
  sshd_usr_local: